### ISSUE TITLE
Indicator Count Test

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#12]
I have tried to test a file but keep getting the execution error below. I did try loading the same file for some of the other tests to make sure there wasn't a problem with the file itself. It loaded fine for the other tests. Here's the error message - let me know if you want to see the whole stack trace:

Server Error in '/' Application.

Key (RDPF_1YR_POST_SEC_RATING) not found for row: 860

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Exception: Key (RDPF_1YR_POST_SEC_RATING) not found for row: 860

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

**Comment by jakepearson** [comment]
Could you send me your data file?

**Comment by jakepearson** [comment]
It looks like you have some bad data.  The error message means that it cannot find any value for the `RDPF_1YR_POST_SEC_RATING` column on the 860th line.  In the sample data you gave me the error was on line 20.

**Comment by jperdue** [comment]
I’m confused. There would have only been 50 or so records in the original file I uploaded, and there were only 18 in the file I sent you. I’ve tried uploading files with a single record and get the same error. Any ideas?

**Comment by jakepearson** [comment]
Hi,
I figured out the problem.  The tool was giving a bad error message.  The
error said something like line 20.  It now says error on line "20-M".  So
there is a problem with the district 20 middle school row.  Please let me
know if that is enough information.

thanks,
Jake
