### ISSUE TITLE
PwrPointsEarnedEqualsPercentOfPwrPoints

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#13]
This test works fine for DPF files, but for SPF files there is a very slight issue. Some high schools will have null values for  1YR_PS_PTS_EARN_TTL and  3YR_PS_PTS_EARN_TTL. Currently, the test flags these cases as errors. Please update the test to allow null values in these fields. Thanks.

**Comment by jakepearson** [comment]
Got it.
