### ISSUE TITLE
Disaggregated Graduation Rate Rollup Points 

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#15]
Allow null values for the following fields:

1YR_PS_GRAD_DSAG_PTS_EARN
1YR_PS_GRAD_DSAG_PTS_ELIG

3YR_PS_GRAD_DSAG_PTS_EARN
3YR_PS_GRAD_DSAG_PTS_ELIG

**Comment by jakepearson** [comment]
Got it.
