### ISSUE TITLE
Participation Overall Met

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#19]
Getting a 'Column not defined' error for the following fields:
- RDPF_1YR_TEST_PARTIC_DNM_COUNT
- RDPF_3YR_TEST_PARTIC_RATING
- RDPF_3YR_TEST_PARTIC_DNM_COUNT
- RDPF_1YR_TEST_PARTIC_RATING
- RDPF_1_3_PARTIC_RATING
- RDPF_1_3_PARTIC_DNM_COUNT

**Comment by jakepearson** [comment]
Got it.
