### ISSUE TITLE
Growth Points Roll-Up Test

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#2]
This test doesn't seem to be working. I created a file that included records that were intentionally set up to generate errors, and the test didn't identify any of them. The test is supposed to make the following checks: 

If RDPF_1YR_GRO_PTS_EARN_ELP +
RDPF_1YR_GRO_PTS_EARN_READ + RDPF_1YR_GRO_PTS_EARN_MATH +
RDPF_1YR_GRO_PTS_EARN_WRITE = RDPF_1YR_GRO_PTS_EARN_TTL, then pass

If RDPF_1YR_GRO_PTS_ELIG_ELP + RDPF_1YR_GRO_PTS_ELIG_READ + RDPF_1YR_GRO_PTS_ELIG_MATH + RDPF_1YR_GRO_PTS_ELIG_WRITE = RDPF_1YR_GRO_PTS_ELIG_TTL, then pass

If RDPF_3YR_GRO_PTS_EARN_ELP + RDPF_3YR_GRO_PTS_EARN_READ + RDPF_3YR_GRO_PTS_EARN_MATH + RDPF_3YR_GRO_PTS_EARN_WRITE = RDPF_3YR_GRO_PTS_EARN_TTL, then pass

If RDPF_3YR_GRO_PTS_ELIG_ELP + RDPF_3YR_GRO_PTS_ELIG_READ + RDPF_3YR_GRO_PTS_ELIG_MATH + RDPF_3YR_GRO_PTS_ELIG_WRITE = RDPF_3YR_GRO_PTS_ELIG_TTL, then pass

**Comment by jakepearson** [comment]
I believe this is complete in the test "GrowthContentPointsSum"

**Comment by jperdue** [comment]
You're right. That test does it. Thanks!
