### ISSUE TITLE
Participation Rating

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#21]
Allow null values:
- 1YR_PARTIC_DN_READ
- 1YR_PARTIC_DN_MATH
- 1YR_PARTIC_DN_WRITE
- 1YR_PARTIC_DN_SCI
- 3YR_PARTIC_DN_READ
- 3YR_PARTIC_DN_MATH
- 3YR_PARTIC_DN_WRITE
- 3YR_PARTIC_DN_SCI

**Comment by jakepearson** [comment]
Let's ask @lysdawn about this one.  It looks like we specifically wrote code to fail this test if those values aren't defined.

**Comment by jperdue** [comment]
Okay. I'll ask her and Marie about it today.
