### ISSUE TITLE
Participation Rate Calculation 

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#22]
Allow null values:
- 1YR_PARTIC_NM_WRITE
- 1YR_PARTIC_NM_SCI
- 1YR_PARTIC_NM_READ
- 1YR_PARTIC_NM_MATH
- 3YR_PARTIC_NM_WRITE
- 3YR_PARTIC_NM_SCI
- 3YR_PARTIC_NM_READ
- 3YR_PARTIC_NM_MATH

**Comment by jakepearson** [comment]
I think I fixed this, but please check the code to be sure.
