### ISSUE TITLE
Growth Content Points Sum

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#24]
This test checks to see that the values in the one- and three-year GRO_PTS_EARN_TTL and GRO_PTS_ELIG_TTL fields are equal to the sums of the values in the individual growth points earned and eligible fields: 

1YR_GRO_PTS_EARN_TTL = sum(1YR_GRO_PTS_EARN_ELP, 1YR_GRO_PTS_EARN_READ, 1YR_GRO_PTS_EARN_MATH, 1YR_GRO_PTS_EARN_WRITE)

3YR_GRO_PTS_EARN_TTL = sum(3YR_GRO_PTS_EARN_ELP, 3YR_GRO_PTS_EARN_READ, 3YR_GRO_PTS_EARN_MATH, 3YR_GRO_PTS_EARN_WRITE)

1YR_GRO_PTS_ELIG_TTL = sum(1YR_GRO_PTS_ELIG_ELP, 1YR_GRO_PTS_ELIG_READ, 1YR_GRO_PTS_ELIG_MATH, 1YR_GRO_PTS_ELIG_WRITE)

3YR_GRO_PTS_ELIG_TTL = sum(3YR_GRO_PTS_ELIG_ELP, 3YR_GRO_PTS_ELIG_READ, 3YR_GRO_PTS_ELIG_MATH, 3YR_GRO_PTS_ELIG_WRITE)

Currently, the test is generating errors where there are null values or other unexpected values in the totals fields. The test needs to be updated to allow cases where the totals are null or where the values in the totals fields are dashes. The code could be rewritten to ignore these cases altogether, or the values could simply be treated as zeros. If you do the latter, null values and dashes in the individual growth points fields would also need to be treated as zeros, so that the sum of the 0 values would total up to 0.

**Comment by jakepearson** [comment]
Are you saying all the values in a group:

`1YR_GG_PTS_EARN_READ = sum(1YR_GG_BPA_PTS_EARN_READ, 1YR_GG_ELL_PTS_EARN_READ, 1YR_GG_DIS_PTS_EARN_READ, 1YR_GG_MIN_PTS_EARN_READ, 1YR_GG_FRL_PTS_EARN_READ)`

need to be null for the test to pass or just the total column?

**Comment by jperdue** [comment]
The test should pass if the total column is null or has a dash in cases where there actually were no values to sum up. If there were values to sum up, then the total shouldn't be null. We would want the test to catch cases where there were valid values in one or more of the summed fields but a null or a dash in the total field.
