### ISSUE TITLE
Growth Gaps Points Rollup

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#25]
This test checks to see that the values in the one- and three-year GG_PTS_EARN and GG_PTS_ELIG fields for each content area are equal to the sums of the values in the individual growth gap points earned and eligible fields:

1YR_GG_PTS_EARN_READ = sum(1YR_GG_BPA_PTS_EARN_READ, 1YR_GG_ELL_PTS_EARN_READ, 1YR_GG_DIS_PTS_EARN_READ, 1YR_GG_MIN_PTS_EARN_READ, 1YR_GG_FRL_PTS_EARN_READ)

1YR_GG_PTS_ELIG_READ = sum(1YR_GG_BPA_PTS_ELIG_READ, 1YR_GG_ELL_PTS_ELIG_READ, 1YR_GG_DIS_PTS_ELIG_READ, 1YR_GG_MIN_PTS_ELIG_READ, 1YR_GG_FRL_PTS_ELIG_READ)

3YR_GG_PTS_EARN_READ = sum(3YR_GG_BPA_PTS_EARN_READ, 3YR_GG_ELL_PTS_EARN_READ, 3YR_GG_DIS_PTS_EARN_READ, 3YR_GG_MIN_PTS_EARN_READ, 3YR_GG_FRL_PTS_EARN_READ)

3YR_GG_PTS_ELIG_READ = sum(3YR_GG_BPA_PTS_ELIG_READ, 3YR_GG_ELL_PTS_ELIG_READ, 3YR_GG_DIS_PTS_ELIG_READ, 3YR_GG_MIN_PTS_ELIG_READ, 3YR_GG_FRL_PTS_ELIG_READ)

1YR_GG_PTS_EARN_MATH = sum(1YR_GG_BPA_PTS_EARN_MATH, 1YR_GG_ELL_PTS_EARN_MATH, 1YR_GG_DIS_PTS_EARN_MATH, 1YR_GG_MIN_PTS_EARN_MATH, 1YR_GG_FRL_PTS_EARN_MATH)

1YR_GG_PTS_ELIG_MATH = sum(1YR_GG_BPA_PTS_ELIG_MATH, 1YR_GG_ELL_PTS_ELIG_MATH, 1YR_GG_DIS_PTS_ELIG_MATH, 1YR_GG_MIN_PTS_ELIG_MATH, 1YR_GG_FRL_PTS_ELIG_MATH)

3YR_GG_PTS_EARN_MATH = sum(3YR_GG_BPA_PTS_EARN_MATH, 3YR_GG_ELL_PTS_EARN_MATH, 3YR_GG_DIS_PTS_EARN_MATH, 3YR_GG_MIN_PTS_EARN_MATH, 3YR_GG_FRL_PTS_EARN_MATH)

3YR_GG_PTS_ELIG_MATH = sum(3YR_GG_BPA_PTS_ELIG_MATH, 3YR_GG_ELL_PTS_ELIG_MATH, 3YR_GG_DIS_PTS_ELIG_MATH, 3YR_GG_MIN_PTS_ELIG_MATH, 3YR_GG_FRL_PTS_ELIG_MATH)

1YR_GG_PTS_EARN_WRITE = sum(1YR_GG_BPA_PTS_EARN_WRITE, 1YR_GG_ELL_PTS_EARN_WRITE, 1YR_GG_DIS_PTS_EARN_WRITE, 1YR_GG_MIN_PTS_EARN_WRITE, 1YR_GG_FRL_PTS_EARN_WRITE)

1YR_GG_PTS_ELIG_WRITE = sum(1YR_GG_BPA_PTS_ELIG_WRITE, 1YR_GG_ELL_PTS_ELIG_WRITE, 1YR_GG_DIS_PTS_ELIG_WRITE, 1YR_GG_MIN_PTS_ELIG_WRITE, 1YR_GG_FRL_PTS_ELIG_WRITE)

3YR_GG_PTS_EARN_WRITE = sum(3YR_GG_BPA_PTS_EARN_WRITE, 3YR_GG_ELL_PTS_EARN_WRITE, 3YR_GG_DIS_PTS_EARN_WRITE, 3YR_GG_MIN_PTS_EARN_WRITE, 3YR_GG_FRL_PTS_EARN_WRITE)

3YR_GG_PTS_ELIG_WRITE = sum(3YR_GG_BPA_PTS_ELIG_WRITE, 3YR_GG_ELL_PTS_ELIG_WRITE, 3YR_GG_DIS_PTS_ELIG_WRITE, 3YR_GG_MIN_PTS_ELIG_WRITE, 3YR_GG_FRL_PTS_ELIG_WRITE)

This test also checks the values in the one- and three-year GG_PTS_EARN_TTL and GG_PTS_ELIG_TTL fields. These should equal the sums of the content area totals: 

1YR_GG_PTS_EARN_TTL = sum(1YR_GG_PTS_EARN_READ, 1YR_GG_PTS_EARN_MATH, 1YR_GG_PTS_EARN_WRITE)

1YR_GG_PTS_ELIG_TTL = sum(1YR_GG_PTS_ELIG_READ, 1YR_GG_PTS_ELIG_MATH, 1YR_GG_PTS_ELIG_WRITE)

3YR_GG_PTS_EARN_TTL = sum(3YR_GG_PTS_EARN_READ, 3YR_GG_PTS_EARN_MATH, 3YR_GG_PTS_EARN_WRITE)

3YR_GG_PTS_ELIG_TTL = sum(3YR_GG_PTS_ELIG_READ, 3YR_GG_PTS_ELIG_MATH, 3YR_GG_PTS_ELIG_WRITE)

Currently, the test is generating errors where there are null values or other unexpected values in the content area totals fields and the overall totals fields: 

1YR_GG_PTS_EARN_READ 
1YR_GG_PTS_ELIG_READ 
3YR_GG_PTS_EARN_READ 
3YR_GG_PTS_ELIG_READ 
1YR_GG_PTS_EARN_MATH 
1YR_GG_PTS_ELIG_MATH 
3YR_GG_PTS_EARN_MATH 
3YR_GG_PTS_ELIG_MATH 
1YR_GG_PTS_EARN_WRITE 
1YR_GG_PTS_ELIG_WRITE 
3YR_GG_PTS_EARN_WRITE 
3YR_GG_PTS_ELIG_WRITE
1YR_GG_PTS_EARN_TTL 
1YR_GG_PTS_ELIG_TTL
3YR_GG_PTS_EARN_TTL 
3YR_GG_PTS_ELIG_TTL 

The test needs to be updated to allow cases where the totals are null or where the values in the totals fields are dashes. The code could be rewritten to ignore these cases altogether, or the values could simply be treated as zeros. If you do the latter, null values and dashes in the individual growth gaps points fields would also need to be treated as zeros, so that the sum of the 0 values would total up to 0.

**Comment by jakepearson** [comment]
Are you saying all the values in a group:

`1YR_GG_PTS_EARN_READ = sum(1YR_GG_BPA_PTS_EARN_READ, 1YR_GG_ELL_PTS_EARN_READ, 1YR_GG_DIS_PTS_EARN_READ, 1YR_GG_MIN_PTS_EARN_READ, 1YR_GG_FRL_PTS_EARN_READ)`

need to be null for the test to pass or just the total column?

**Comment by jperdue** [comment]
Same as with the other. The total column should only be null in cases where there are no values in any of the fields that contribute to the sum. If one or more contributing column has a valid value, then the total fields should reflect the actual sum of those values. We'd want the test to flag instances where that isn't the case, that is, where the total is null but there are actual values that should be getting summed up.
