### ISSUE TITLE
Growth Points Earned Equals Percent Of Growth Points

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#26]
This test checks to see that the percent calculations for all of the one- and three-year GRO_PCT_PTS_EARN and GG_PCT_PTS_EARN fields are correct:

1YR_GRO_PCT_PTS_EARN_TTL = 1YR_GRO_PTS_EARN_TTL/1YR_GRO_PTS_ELIG_TTL

3YR_GRO_PCT_PTS_EARN_TTL = 3YR_GRO_PTS_EARN_TTL/3YR_GRO_PTS_ELIG_TTL

1YR_GG_PCT_PTS_EARN_READ = 1YR_GG_PTS_EARN_READ/1YR_GG_PTS_ELIG_READ

3YR_GG_PCT_PTS_EARN_READ = 3YR_GG_PTS_EARN_READ/3YR_GG_PTS_ELIG_READ

1YR_GG_PCT_PTS_EARN_MATH = 1YR_GG_PTS_EARN_MATH/1YR_GG_PTS_ELIG_MATH

3YR_GG_PCT_PTS_EARN_MATH = 3YR_GG_PTS_EARN_MATH/3YR_GG_PTS_ELIG_MATH

1YR_GG_PCT_PTS_EARN_WRITE = 1YR_GG_PTS_EARN_WRITE/1YR_GG_PTS_ELIG_WRITE

3YR_GG_PCT_PTS_EARN_WRITE = 3YR_GG_PTS_EARN_WRITE/3YR_GG_PTS_ELIG_WRITE

1YR_GG_PCT_PTS_EARN_TTL = 1YR_GG_PTS_EARN_TTL/1YR_GG_PTS_ELIG_TTL

3YR_GG_PCT_PTS_EARN_TTL = 3YR_GG_PTS_EARN_TTL/3YR_GG_PTS_ELIG_TTL

Currently, the test is generating errors where there are null values or other unexpected values in the PCT_PTS_EARN fields. The test needs to be updated to allow cases where the totals are null or where the values in the totals fields are dashes. The code should be rewritten to ignore nulls or dashes in these fields in cases where there is also a null value or a dash in either the PTS_EARN or PTS_ELIG field. This last condition is to make sure the test does still catch erroneous cases where there should be a valid percent calculation but is not.

**Comment by jakepearson** [comment]
Got it.
