### ISSUE TITLE
Academic Growth and Growth Gaps- Met Adequate Growth Tests

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#3]
I don't see an existing test for this, although the code for the existing Growth Points Rollup test looks like it might do it. The test is supposed to check the following: 

If MGP – AGP > = 0 and Made AGP = YES, then pass
If MGP - AGP < 0 and Made AGP = NO, then pass
If MGP equals “-“ and AGP equals “-“  and Made AGP equals “-“ then pass
If MGP equals “ “ and AGP equals “ “  and Made AGP equals “ “ then pass

I did just try running a test file against the Points Rollup test, but it didn't quite work.

**Comment by jakepearson** [comment]
HI Josh,
We just looked through the code and that test is a part of growth points roll-up. Can you let us know what part of it didn't work when you ran the test file?

Also, we removed the check for ELP growth for this year, since there will never be AGPs in 2013.

Thanks,
Alyssa

**Comment by jperdue** [comment]
Okay, the Growth Points Roll-Up test is working to identify errors around "Met AGP". However, it does not seem to be working to test the actual points roll-up. I looked at the code again, and it just doesn't seem to be in there. It should look something like the Growth Gaps Points Roll-Up code, just checking the GRO fields instead of the GG fields.

**Comment by jakepearson** [comment]
I'll have to ask Alyssa to help me when she gets back.

**Comment by jakepearson** [comment]
We think this is already tested in "Growth Content Points Sum".  Please take a look.
