### ISSUE TITLE
Participation Overall Met

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#30]
Not sure what's going on with this. The test is generating 'Column not defined' errors for all records for the following fields:

RDPF_1YR_TEST_PARTIC_DNM_COUNT
RDPF_3YR_TEST_PARTIC_DNM_COUNT
RDPF_1_3_PARTIC_DNM_COUNT

Does the 'RDPF_' prefix need to be removed from the field names in the code?

**Comment by jakepearson** [comment]
You're correct.  The `RDPF_` shouldn't be in column name.
