### ISSUE TITLE
Percent Of Points

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#32]
This test is meant to validate the one- and three-year PCT_PTS_EARN calculations for Achievement, Growth, Growth Gaps, and Post Secondary:

1_3_ACHIEVE_PCT_PTS_EARN = 1_3_ACHIEVE_PTS_ELIG/1_3_ACHIEVE_PTS_EARN

1_3_GROWTH_PCT_PTS_EARN = 1_3_GROWTH_PTS_ELIG/1_3_GROWTH_PTS_EARN

1_3_GRO_GAPS_PCT_PTS_EARN = 1_3_GRO_GAPS_PTS_ELIG/1_3_GRO_GAPS_PTS_EARN

1_3_POST_SEC_PCT_PTS_EARN = 1_3_POST_SEC_PTS_ELIG/1_3_POST_SEC_PTS_EARN

1YR_ACHIEVE_PCT_PTS_EARN = 1YR_ACHIEVE_PTS_ELIG/1YR_ACHIEVE_PTS_EARN

1YR_GROWTH_PCT_PTS_EARN = 1YR_GROWTH_PTS_ELIG/1YR_GROWTH_PTS_EARN

1YR_GRO_GAPS_PCT_PTS_EARN = 1YR_GRO_GAPS_PTS_ELIG/1YR_GRO_GAPS_PTS_EARN

1YR_POST_SEC_PCT_PTS_EARN = 1YR_POST_SEC_PTS_ELIG/1YR_POST_SEC_PTS_EARN

3YR_ACHIEVE_PCT_PTS_EARN = 3YR_ACHIEVE_PTS_ELIG/3YR_ACHIEVE_PTS_EARN

3YR_GROWTH_PCT_PTS_EARN = 3YR_GROWTH_PTS_ELIG/3YR_GROWTH_PTS_EARN

3YR_GRO_GAPS_PCT_PTS_EARN = 3YR_GRO_GAPS_PTS_ELIG/3YR_GRO_GAPS_PTS_EARN

3YR_POST_SEC_PCT_PTS_EARN = 3YR_POST_SEC_PTS_ELIG/3YR_POST_SEC_PTS_EARN

The test is flagging errors when the value in the PTS_EARN field is null. It should be updated to allow null values for PTS_ELIG, PTS_EARN, and PCT_PTS_EARN.

**Comment by jakepearson** [comment]
Does that mean it should pass if all of the columns are null, or should it pass if only one of the columns is null?

**Comment by jperdue** [comment]
If the PCT field is null and either the points eligible or points earned field is also null, then it should pass. The idea is that there wouldn't  be a null value in the PCT field unless there was also a null value in at least one of the two fields referenced in the calculation.
