### ISSUE TITLE
Co Alt One Percent Cap Exceed

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#34]
The test is still flagging cases where COALT_CAP_1PCTN is equal to COALT_CAP_PA_N.

**Comment by jakepearson** [comment]
Could you send me an example data file?  Ideally with just one data row.

**Comment by jperdue** [comment]
Need to add fields for Social Studies:

"1YR_COALT_CAP_EXCD_SOC", "1YR_COALT_CAP_PA_N_SOC", "1YR_COALT_CAP_1PCTN_SOC", "1YR_COALT_CAP_NEXCD_SOC"

"3YR_COALT_CAP_EXCD_SOC", "3YR_COALT_CAP_PA_N_SOC", "3YR_COALT_CAP_1PCTN_SOC", "3YR_COALT_CAP_NEXCD_SOC"

**Comment by jakepearson** [comment]
Done.
