### ISSUE TITLE
Overall Total Rating

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#36]
This test is giving the column undefined error for a couple of fields when I run the DPF file: 

A_TTL_SPF_RATING_CALC
A_TTL_SPF_RATING_OFFICIAL

I think the issue is that 'SPF' appears in the middle of the field name, not just as the 'RSPF' prefix. So, in the DPF file, the field names are:

A_TTL_DPF_RATING_CALC
A_TTL_DPF_RATING_OFFICIAL

Is there a way to make the test look for either one or the other?

**Comment by lysdawn** [comment]
Josh- this is part of what we fixed tonight. It was also an issue of the
different rating names in the DPF- "performance" versus "accredited".
