### ISSUE TITLE
CoAltExceedNCount.cs

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#38]
Need to add fields for Social Studies:

"1YR_COALT_CAP_EXCD_SOC", "1YR_COALT_CAP_PA_N_SOC", "1YR_COALT_CAP_1PCTN_SOC", "1YR_COALT_CAP_NEXCD_SOC"

"3YR_COALT_CAP_EXCD_SOC", "3YR_COALT_CAP_PA_N_SOC", "3YR_COALT_CAP_1PCTN_SOC", "3YR_COALT_CAP_NEXCD_SOC"

**Comment by jakepearson** [comment]
Done.
