### ISSUE TITLE
CoAltOnePercentExceedsAdjustment

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#39]
Update to include Soc Studies

yield return new Tuple<string, string, string>("1YR_PARTIC_NM_NOCAP_SOC", "1YR_PARTIC_NM_SOC", "1YR_COALT_CAP_NEXCD_SOC");

yield return new Tuple<string, string, string>("3YR_PARTIC_NM_NOCAP_SOC", "3YR_PARTIC_NM_SOC", "3YR_COALT_CAP_NEXCD_SOC");

**Comment by jakepearson** [comment]
Done.
