### ISSUE TITLE
ParticipationRating

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#40]
Add fields for Soc Studies:

"1YR_PARTIC_RATING_SOC", "1YR_PARTIC_PCT_TEST_SOC", "1YR_PARTIC_DN_SOC"

"3YR_PARTIC_RATING_SOC", "3YR_PARTIC_PCT_TEST_SOC", "3YR_PARTIC_DN_SOC"

**Comment by jakepearson** [comment]
Done.
