### ISSUE TITLE
ParticipationRateCalculation

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#42]
Add Soc Studies fields: 

"1YR_PARTIC_PCT_TEST_SOC", "1YR_PARTIC_NM_SOC", "1YR_PARTIC_DN_SOC"

"3YR_PARTIC_PCT_TEST_SOC", "3YR_PARTIC_NM_SOC", "3YR_PARTIC_DN_SOC"

**Comment by jakepearson** [comment]
Done.
