### ISSUE TITLE
Indicator Count Test

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#5]
An additional test is needed to determine the number of valid indicators within the 1 and 3 year SPF/DPF. The rules are as follows: 

If RDPF_1YR_INDICATOR_NCOUNT = 4 and RDPF_1YR_ACHIEVE_RATING, RDPF_1YR_GROWTH_RATING, RDPF_1YR_GRO_GAPS_RATING, and RDPF_1YR_POST_SEC_RATING not equal to “ “ or “-“, then pass

If RDPF_1YR_INDICATOR_NCOUNT = 3 and RDPF_1YR_ACHIEVE_RATING, RDPF_1YR_GROWTH_RATING, RDPF_1YR_GRO_GAPS_RATING, and RDPF_1YR_POST_SEC_RATING equal to VALUE and one RATING equal to “ “ or “-“, then pass

If RDPF_1YR_INDICATOR_NCOUNT = 2 and RDPF_1YR_ACHIEVE_RATING, RDPF_1YR_GROWTH_RATING, RDPF_1YR_GRO_GAPS_RATING, and RDPF_1YR_POST_SEC_RATING equal to VALUE and two RATINGS equal to “ “ or “-“, then pass

If RDPF_1YR_INDICATOR_NCOUNT =1 and RDPF_1YR_ACHIEVE_RATING, RDPF_1YR_GROWTH_RATING, RDPF_1YR_GRO_GAPS_RATING, and RDPF_1YR_POST_SEC_RATING equal to VALUE and three RATINGS equal to “ “ or “-“, then pass

If RDPF_1YR_INDICATOR_NCOUNT =0 and RDPF_1YR_ACHIEVE_RATING, RDPF_1YR_GROWTH_RATING, RDPF_1YR_GRO_GAPS_RATING, and RDPF_1YR_POST_SEC_RATING equal to “ “ or “-“, then pass

If RDPF_3YR_INDICATOR_NCOUNT = 4 and RDPF_3YR_ACHIEVE_RATING, RDPF_3YR_GROWTH_RATING, RDPF_3YR_GRO_GAPS_RATING, and RDPF_3YR_POST_SEC_RATING not equal to “ “ or “-“, then pass

If RDPF_3YR_INDICATOR_NCOUNT = 3 and RDPF_3YR_ACHIEVE_RATING, RDPF_3YR_GROWTH_RATING, RDPF_3YR_GRO_GAPS_RATING, and RDPF_3YR_POST_SEC_RATING equal to VALUE and one RATING equal to “ “ or “-“, then pass

If RDPF_3YR_INDICATOR_NCOUNT = 2 and RDPF_3YR_ACHIEVE_RATING, RDPF_3YR_GROWTH_RATING, RDPF_3YR_GRO_GAPS_RATING, and RDPF_3YR_POST_SEC_RATING equal to VALUE and two RATINGS equal to “ “ or “-“, then pass

If RDPF_3YR_INDICATOR_NCOUNT =1 and RDPF_3YR_ACHIEVE_RATING, RDPF_3YR_GROWTH_RATING, RDPF_3YR_GRO_GAPS_RATING, and RDPF_3YR_POST_SEC_RATING equal to VALUE and three RATINGS equal to “ “ or “-“, then pass

If RDPF_3YR_INDICATOR_NCOUNT =0 and RDPF_3YR_ACHIEVE_RATING, RDPF_3YR_GROWTH_RATING, RDPF_3YR_GRO_GAPS_RATING, and RDPF_3YR_POST_SEC_RATING equal to “ “ or “-“, then pass

**Comment by jakepearson** [comment]
This is complete.  It is called Indicator Count.

thanks,
Jake

**Comment by jperdue** [comment]
Tried to test a file but got the execution error below. I did try loading the same file for some of the other tests to make sure there wasn't a problem with the file itself. It loaded fine for the other tests. Here's the error message - let me know if you want to see the whole stack trace: 

Server Error in '/' Application.

Key (RDPF_1YR_POST_SEC_RATING) not found for row: 860

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: Key (RDPF_1YR_POST_SEC_RATING) not found for row: 860

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
