### ISSUE TITLE
CoAltOnePercentCapExceed

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#7]
When PA_N is greater than 1PCTN, CAP_EXCD should be "Yes". The test should flag records that have PA_N greater than 1PCTN but have "No" in the CAP_EXCD field. Currently, it's not identifying these errors.

**Comment by jakepearson** [comment]
I believe I implemented what you wanted.  Does this look correct?

```
var excdValue = row[excdColumn].ToLower();
if(excdValue == "yes")
{
    AssertGreaterThan(row, panColumn, pctnColumn, errors);
}
else if (excdValue == "no")
{
    AssertGreaterThan(row, pctnColumn, panColumn, errors);
}
```

**Comment by jakepearson** [comment]
It is in production so you can test it as well.

**Comment by jperdue** [comment]
Thanks Jake. This is working. One minor thing, when you have a chance. Could you change how the test handles cases where 1YR_COALT_CAP_1PCTN = 0? In these cases, records should pass if 1YR_COALT_CAP_PA_N_READ is null or if 1YR_COALT_CAP_PA_N also equals zero. Sorry, I know it's tedious.

**Comment by jakepearson** [comment]
Please double check this, we weren't totally sure we implemented what you asked for.

**Comment by jperdue** [comment]
I think you got it. Thanks!
