### ISSUE TITLE
OfficialDataMatchesOneOrThreeYearData

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#8]
For the following fields, null values are okay, so the "Value Undefined" error shouldn't pop up. 

RSPF_1YR_POST_SEC_RATING
RSPF_1YR_POST_SEC_PCT_PTS_EARN
RSPF_1YR_POST_SEC_PTS_EARN
RSPF_1YR_POST_SEC_PTS_ELIG
RSPF_3YR_POST_SEC_RATING
RSPF_3YR_POST_SEC_PCT_PTS_EARN
RSPF_3YR_POST_SEC_PTS_EARN
RSPF_3YR_POST_SEC_PTS_ELIG

**Comment by jakepearson** [comment]
Give it a go.

**Comment by jperdue** [comment]
Those are working now, but I left two off the list. Can you make these nullable as well?

1_3_POST_SEC_PTS_ELIG
1_3_POST_SEC_PTS_ELIG
