### ISSUE TITLE
Participation Rate Tests

### ISSUE THREAD

**Issue by jperdue** [jakepearson/cde-export#9]
Hey Jake,

There are several sets of rules around participation rates and ratings, and it seems like the three existing tests cover almost all of them. The rule that seems to be missing a test applies to the values in the  1_3_PARTIC_RATING; 1YR_PARTIC_RATING; and RDPF_1YR_PARTIC_RATING fields. We need a test that confirms that ratings are being determined as follows: 

IF RDPF_1_3_PARTIC_DNM_COUNT > = 2
THEN RDPF_1_3_PARTIC_RATING= “Does Not Meet 95% Participation Rate”

IF RDPF_1_3_PARTIC_DNM_COUNT < 2
THEN RDPF_1_3_PARTIC_RATING= “Meets 95% Participation Rate”

IF RDPF_1_3_PARTIC_DNM_COUNT = “ “ 
THEN RDPF_1_3_PARTIC_RATING = “ “ 

The same logic should apply to the relationships between the 1YR_PARTIC_DNM_COUNT  and 1YR_PARTIC_RATING fields, as well as between the 3YR_PARTIC_DNM_COUNT and 3YR_PARTIC_RATING fields. 

I know this one might need to wait till Alyssa gets back, but I wanted to make a note of it while I'm working on it. Thanks for all your help.

**Comment by jperdue** [comment]
Also, it looks like the ParticipationRateCalculation test might be repeated in the ParticipationRating test. If so, I think we might be able to eliminate the RateCalculation test, just to make things clearer.

**Comment by jakepearson** [comment]
All set.
